### PR TITLE
Rename LGraph to Lgraph and Index_ID to Index_id in all the classes

### PR DESCRIPTION
**Pull request by bokket**
The condition of my machine:
image

Local build and test pass:
image
image

In addition, I have some doubts: except for the separate variables in some classes, it is similar to:**GLargh**, but in the underscore method of **get_class_glargh**, I don’t know whether **L** should be changed to **l** (for backward compatibility in a certain sense, I may be confused This case)

---
This change is [Reviewable](https://reviewable.io/reviews/masc-ucsc/livehd/201)

### CODE REVIEW

**Comment by jesec** [comment]
Um... I don't think this is necessary. Variable naming is already consistent and coherent. The change is confusing and breaks multiple naming conventions. 

FYI: `//main:all` is not a test target. Check out CI workflows, related commits and documentations for how to build and test LiveHD. 

Additionally, builds are failing with this change. See https://github.com/masc-ucsc/livehd/pull/201/checks .

**Comment by bokket** [comment]
> 嗯...我认为这是没有必要的。可变命名已经是一致和连贯的。这种变化令人困惑，并打破了多个命名约定。
> 
> 仅供参考：不是测试目标。查看 CI 工作流、相关提交和文档，了解如何构建和测试 LiveHD。`//main:all`
> 
> 此外，构建在进行此更改时也发生故障。见[https://github.com/masc-ucsc/livehd/pull/201/checks。](https://github.com/masc-ucsc/livehd/pull/201/checks)

reference to https://github.com/masc-ucsc/livehd/blob/master/docs/cleanup.md
yes,In a sense, this caused some problems, but before I changed it, there were already some inconsistencies in the long function naming. As for the github workflow and related submissions, I don't know why it can be passed locally.

**Comment by renau** [comment]
There are issues with this pull request. It does not run/compile like before. E.g:
```
core/tests/tree_lgdb_setup.hpp:215:28: error: 'const class Graph_library' has no member named 'each_lgraph'; did you mean 'each_Lgraph'?
  215 |     lg_root->get_library().each_lgraph([this](Lg_type_id lgid, std::string_view name) {
```

I am fine with the changes, but the code should not just stop working/compiling. Try to fix it and make sure that the compile and tests are as good as before the change.

**Comment by renau** [comment]
The coding style is at https://github.com/masc-ucsc/livehd/blob/master/docs/Style.md
Only classes start with upper case (first character only), methods and variables are always lower case, with the exception of defines that are all upper case.
We never use camelCase, we separate words with underscores (E.g: get_bits)

**Pull request closed without merging**
