### PR TITLE
Switch to rules_hdl

### PR DESCRIPTION
**Pull request by jesec**
This change is [Reviewable](https://reviewable.io/reviews/masc-ucsc/livehd/210)

### CODE REVIEW

**Review by mithro — COMMENTED** [review]
Super excited to see you planning to switch to https://github.com/hdl/bazel_rules_hdl! 

Is there anything we can do to help here?

**Comment by mithro** [comment]
FYI - @per-gron @hzeller @QuantamHD @eine

**Comment by jesec** [comment]
> Super excited to see you planning to switch to https://github.com/hdl/bazel_rules_hdl!
> 
> Is there anything we can do to help here?

Thanks. rules_hdl is quite useful.

I have applied some patches (https://github.com/jesec/bazel_rules_hdl) to get things working.

**Comment by mithro** [comment]
We are super interested in getting more groups using it and collaborating, so please do send your changes for review.

**Pull request merged**
