### PR TITLE
Remove set2attr_set_get

### PR DESCRIPTION
**Pull request by bokket**
See commit messages for more info.

---
This change is [Reviewable](https://reviewable.io/reviews/masc-ucsc/livehd/207)

### CODE REVIEW

**Review by swang203 — COMMENTED** [review]
Please stop touching the following codes without new features adding.
(1)lnast.*pp
(2)lcompiler.*pp
(3)pass_compiler.*pp. 
(4)lnast_tolg.*pp
(5)cprop.*pp
(6)bitwidth.*pp
I'm in charge of maintaining these blocks. 
There are heavy changes going on underneath. 
If you found bugs, please create issues.

**Comment by bokket** [comment]
> 请停止触摸以下代码，无需添加新功能。
> （1）lnast.*pp
> （2）lcompiler.*pp
> （3）pass_compiler.*pp.（4）lnast_tolg.*pp
> 
> （5）cprop.*pp
> （6）位宽。*pp
> 我负责维护这些块。
> 下面发生了巨大的变化。
> 如果您发现错误，请创建问题。

ok

**Comment by swang203** [comment]
Hi, 
Thanks for understanding and help.
I think the best way to start help and involved is to choose one of the projects on this lists
[https://github.com/masc-ucsc/livehd/blob/master/docs/projects.md]
we have planed many interesting projects based on LiveHD infrastructure,
maybe you could pick the one most excited you to start? (but some of them may be taken over by other students, you could check with Prof.Jose)

**Comment by bokket** [comment]
> Hi,
> Thanks for understanding and help.
> I think the best way to start help and involved is to choose one of the projects on this lists
> [https://github.com/masc-ucsc/livehd/blob/master/docs/projects.md]
> we have planed many interesting projects based on LiveHD infrastructure,
> maybe you could pick the one most excited you to start? (but some of them may be taken over by other students, you could check with Prof.Jose)

yes，sir. I have contacted mentor for the proposal of grpc client.  I left a cleanup task referring to mentor: https://github.com/masc-ucsc/livehd/blob/master/docs/cleanup.md. But I don't know this about some other things.  If there is a problem, I am deeply sorry

**Comment by swang203** [comment]
never mind. I don't know you've contacted Jose and choose this task.
The reason is that the firrrtl compilation regression is broken and we're fixing it right now. 
No passing regression (not a good thing) means it can not guarantee your change is correct.
So maybe after I brought it back, then you could continue the clean-up with a working firrtl compiler regression (10days).

**Comment by bokket** [comment]
> 没关系。我不知道你已经联系了何塞并选择了这个任务。
> 原因是 firtl 编译回归已损坏，我们正在修复它。
> 没有通过回归（不是一件好事）意味着它不能保证你的改变是正确的。
> 所以， 也许我把它带回来后， 然后你可以继续清理与工作 firrtl 编译器回归 （10 天） 。

Received, I will continue to comply

**Pull request closed without merging**
